FROM node:8.10.0

# Create app directory
WORKDIR /client

ENV PATH /client/node_modules/.bin:$PATH

# Install app dependencies
COPY package*.json ./

RUN npm install

#Bundle app source
COPY . .

EXPOSE 8080

CMD ["npm", "run", "build"]
