module.exports = {
    CalleController: require("./CalleController"),
    CasoController: require("./CasoController"),
    CiudadController: require("./CiudadController"),
    ConsultaController: require("./ConsultaController"),
    HomeController: require("./HomeController"),
    HospitalController: require("./HospitalController"),
    LoginController: require("./LoginController"),
    MedicoController: require("./MedicoController"),
    PacienteController: require("./PacienteController"),
    ParteMedicoController: require("./ParteMedicoController"),
    PruebaController: require("./PruebaController"),
    RecursoController: require("./RecursoController"),
    ReporteController: require("./ReporteController"),
}