module.exports = {
    CalleRepository: require("./CalleRepository"),
    CasoRepository: require("./CasoRepository"),
    CiudadRepository: require("./CiudadRepository"),
    ConsultaRepository: require("./ConsultaRepository"),
    CuentaRepository: require("./CuentaRepository"),
    DireccionRepository: require("./DireccionRepository"),
    HospitalRepository: require("./HospitalRepository"),
    MedicoRepository: require("./MedicoRepository"),
    ParteMedicoRepository: require("./ParteMedicoRepository"),
    PruebaRepository: require("./PruebaRepository"),
    RecursoRepository: require("./RecursoRepository"),
    AdministradorRepository: require("./AdministradorRepository"),
    SesionRepository: require("./SesionRepository"),
};